# Build the docker images and push to dockerhub

language: node_js
node_js:
  - 13

services:
  - docker

# Nothing special to do before install
before_install:
  - echo "No special prebuild instructions" 

script:
# API Feed Build
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker tag udagram-api-feed mwatermanaus/udagram-api-feed:v1
# API User Build
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker tag udagram-api-user mwatermanaus/udagram-api-user:v1
# Front End Build
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker tag udagram-frontend mwatermanaus/udagram-frontend:v1
# Reverse Proxy Build
  - docker build -t udagram-everseproxy ./project/udagram-reverseproxy
  - docker tag reverseproxy mwatermanaus/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mwatermanaus/udagram-api-feed:v1
  - docker push mwatermanaus/udagram-api-user:v1
  - docker push mwatermanaus/udagram-frontend:v1
  - docker push mwatermanaus/udagram-reverseproxy:v1
