# Build the docker images and push to dockerhub

language: node_js
node_js:
  - 13

services:
  - docker

# Nothing special to do before install
before_install:
  - echo "No special prebuild instructions" 

script:
# API Feed Build
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker tag udagram-api-feed mwatermanaus/udagram-api-feed:v3
# API User Build
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker tag udagram-api-user mwatermanaus/udagram-api-user:v3
# Front End Build
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker tag udagram-frontend mwatermanaus/udagram-frontend:v3
# Reverse Proxy Build
  - docker build -t udagram-reverseproxy ./project/udagram-reverseproxy
  - docker tag udagram-reverseproxy mwatermanaus/udagram-reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mwatermanaus/udagram-api-feed:v3
  - docker push mwatermanaus/udagram-api-user:v3
  - docker push mwatermanaus/udagram-frontend:v3
  - docker push mwatermanaus/udagram-reverseproxy:v3
