# Build the docker images and push to dockerhub

language: node_js
node_js:
  - 13

services:
  - docker

# Nothing special to do before install
before_install:
  - echo "No special prebuild instructions" 

# API Feed Build and push
script:
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker tag udagram-api-feed mwatermanaus/udagram-api-feed:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mwatermanaus/udagram-api-feed:v1
