apiVersion: v1
kind: Service
metadata:
  name: udagram-project-frontend
  labels:
    service: udagram-project-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    service: udagram-project-frontend

